export const FETCH_POST_DETAILS_ERROR = 'POSTS/DETAILS/FETCH_POST_DETAILS_ERROR';
export const FETCH_POST_DETAILS_REQUEST = 'POSTS/DETAILS/FETCH_POST_DETAILS_REQUEST';
export const FETCH_POST_DETAILS_RESPONSE = 'POSTS/DETAILS/FETCH_POST_DETAILS_RESPONSE';
export const EDIT_POST_DETAILS_ERROR = 'POSTS/DETAILS/EDIT_POST_DETAILS_ERROR';
export const EDIT_POST_DETAILS_REQUEST = 'POSTS/DETAILS/EDIT_POST_DETAILS_REQUEST';
export const EDIT_POST_DETAILS_RESPONSE = 'POSTS/DETAILS/EDIT_POST_DETAILS_RESPONSE';