export const FETCH_USER_DETAILS_ERROR = 'USERS/DETAILS/FETCH_USER_DETAILS_ERROR';
export const FETCH_USER_DETAILS_REQUEST = 'USERS/DETAILS/FETCH_USER_DETAILS_REQUEST';
export const FETCH_USER_DETAILS_RESPONSE = 'USERS/DETAILS/FETCH_USER_DETAILS_RESPONSE';