export const FETCH_PROFILE_ERROR = 'USERS/FETCH_PROFILE_ERROR';
export const FETCH_PROFILE_REQUEST = 'USERS/FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_RESPONSE = 'USERS/FETCH_PROFILE_RESPONSE';
export const EDIT_PROFILE_ERROR = 'USERS/EDIT_PROFILE_ERROR';
export const EDIT_PROFILE_REQUEST = 'USERS/EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_RESPONSE = 'USERS/EDIT_PROFILE_RESPONSE';