export const FETCH_REQUEST = 'POSTS/POSTLISTS/FETCH_REQUEST';
export const FETCH_ERROR = 'POSTS/POSTLISTS/FETCH_ERROR';
export const FETCH_RESPONSE = 'POSTS/POSTLISTS/FETCH_RESPONSE';
export const ADD_POST_ERROR = 'POSTS/POSTLISTS/ADDPOST/ADD_POST_REQUEST';
export const ADD_POST_REQUEST = 'POSTS/POSTLISTS/ADDPOST/ADD_POST_ERROR';
export const ADD_POST_RESPONSE = 'POSTS/POSTLISTS/ADDPOST/ADD_POST_RESPONSE';


