export const FETCH_USER_PROFILE_ERROR = 'USERS/FETCH_USER_PROFILE_ERROR';
export const FETCH_USER_PROFILE_REQUEST = 'USERS/FETCH_USER_PROFILE_REQUEST';
export const FETCH_USER_PROFILE_RESPONSE = 'USERS/FETCH_USER_PROFILE_RESPONSE';